language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install
  - mkdir $HOME/ci-utils
  - curl -L https://github.com/grunt-tex/ci-utils/tarball/master | tar -zxpC $HOME/ci-utils --strip-components=1
  - PATH=$HOME/ci-utils/texlive/dist/bin/x86_64-linux:$PATH