language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install
  - curl -L https://github.com/grunt-tex/texlive-squashfs/raw/master/out/texlive.tar.xz | tar -JxC ~
install:
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH